title: Samson Emiola Data Analytics Portfolio
logo: data.jpg
description: Data Analyst with two years of experience leveraging Microsoft Excel for process automation and advanced data modelling, writing complex Server Querry Language (SQL) queries for data extraction and analysis, and developing interactive Power BI dashboards to deliver actionable insights and support strategic decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
